# Change these first
owner: IstvanCsVarga # Your GitHub organization or username, where this repository lives
repo: istvanv-dev-upttime # The name of this repository

sites:
  - name: istvanv.dev
    url: https://www.istvanv.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Welcome to my real-time uptime monitor! This page dynamically tracks the status of my projects, leveraging GitHub's innovative Actions, Issues, and Pages. It's a seamless integration that requires no additional servers, showcasing the power and simplicity of GitHub's ecosystem. Curious about setting up your own uptime page? It's free and straightforward. Check out [Upptime on GitHub](https://github.com/upptime/upptime) to get started!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
