owner: IstvanCsVarga
repo: istvanv-dev-upttime # The name of this repository

sites:
  - name: istvanv.dev
    url: https://www.istvanv.dev

status-website:
  theme: dark
  baseUrl: /istvanv-dev-upttime
  logoUrl: https://raw.githubusercontent.com/IstvanCsVarga/istvancsvarga.github.io/master/src/assets/logo.svg
  faviconSvg: https://raw.githubusercontent.com/IstvanCsVarga/istvancsvarga.github.io/master/src/assets/logo.svg
  name: istvanv Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Explore my uptime monitor, powered by GitHub Actions and Pages, providing real-time status updates of my projects. No server needed! Interested in your own? Visit [Upptime on GitHub](https://github.com/upptime/upptime) for a free setup.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
assignees: IstvanCsVarga
